services:

  frontend:
    image: yashrajoria0327/devops-demo-app:${IMAGE_TAG}
    container_name: devops-demo-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - devops-net
    restart: unless-stopped

  backend:
    image: yashrajoria0327/devops-demo-backend:${IMAGE_TAG}
    container_name: devops-demo-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - devops-net
    secrets:
      - mysql_password
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: devops-demo-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "MYSQL_PWD=$$(cat /run/secrets/mysql_root_password) mysqladmin ping -h localhost -u root --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - devops-net
    secrets:
      - mysql_password
      - mysql_root_password
    restart: unless-stopped

networks:
  devops-net:

volumes:
  mysql-data:
    external: true
    name: mysql_data

secrets:
  mysql_password:
    file: /home/devops/.config/devops-demo-app/secrets/mysql_password

  mysql_root_password:
    file: /home/devops/.config/devops-demo-app/secrets/mysql_root_password
